### ISSUE TITLE
Bug: Progress bar display of 0 value

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#1012]
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/93577764/74d1f0b2-64e7-4711-90e9-67bf6a4dca03)
If progress is set to 0% it's apears to be broken (see in the screenshot)

**Comment by akashyeole** [comment]
@verena-ifx 
In the [figma design](https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=37319-13746&mode=design&t=rdDdUbNd4M0Oy8jz-4), when the progress is 0 the text is hidden.
