### ISSUE TITLE
Accordion issue while switching tabs

### ISSUE THREAD

**Issue by ansarishamsu** [Infineon/infineon-design-system-stencil#1036]
Description:

Expansion button for documents in Document History doesn't work correct after switching tabs.

Steps to Reproduce:

Click to a document that has a Document History.
Open Document History and open one of its older or newer version.
 Information in "General", "System", "Workflow Information" fields don't show up even though little arrow indicates that they are open.
After clicking 2 times, it opens as it should be. 

while switching tabs, we can see the height is 0px and while onload expand height is 112px but we have details data for groups and attributes in both cases.
Please find HTML code details in both cases, we have same tags also.
<div class="accordion-content" style="max-height: 112px;"><div class="inner-content"><slot></slot></div></div>

<div class="accordion-content" style="max-height: 0px;"><div class="inner-content"><slot></slot></div></div>
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/162416969/3fd44317-4f5b-442b-b8eb-06b8b65cc3e1)
![image-2024-02-28-18-14-35-957](https://github.com/Infineon/infineon-design-system-stencil/assets/162416969/a28ac30c-b2d7-4672-b016-47652119c360)
![image-2024-02-28-18-15-19-133](https://github.com/Infineon/infineon-design-system-stencil/assets/162416969/51289c5f-c324-4812-bc1c-ce79940a84e9)

Expected Result:

We shouldn't have to click 2 times to see the information in "General", "System", "Workflow Information" fields. These fields should appear expanded.

Actual Result:
Data loading on click of 2 times.

Frequency (1/1, 1/50, 1/100):

Build/Commit:

"@infineon/infineon-design-system-react": "20.38.4",
"@infineon/infineon-design-system-stencil": "20.38.4",

**Comment by tishoyanchev** [comment]
Resolved
