### ISSUE TITLE
Storybook: add a new story page with sub pages

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1038]
Add a new story page called "foundations" below FAQ. 
In it, add all the sub story pages that will be provided by designers. Each sub story page will contain text and visual description of our tokens in a mdx format similar to Usage.mdx.

**Comment by verena-ifx** [comment]
What is missing right now: @SergejLust 
- Iconography image: IconTextColorAlignment
- Logo image: BorderRadius100px

**Comment by SergejLust** [comment]
Files for typography

[Typography-images.zip](https://github.com/In
[Typography (1).zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849052/Typography.1.zip)
fineon/infineon-design-system-stencil/files/14849050/Typography-images.zip)

**Comment by SergejLust** [comment]
[Typography.zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849175/Typography.zip)
[Typography-images.zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849176/Typography-images.zip)
[Spacing-images.zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849177/Spacing-images.zip)
[Spacing.zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849178/Spacing.zip)
[Color.zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849179/Color.zip)
[Color-images.zip](https://github.com/Infineon/infineon-design-system-stencil/files/14849180/Color-images.zip)

**Comment by SergejLust** [comment]
@verena-ifx  I've uploaded the missing foundation assets. By the way: "States" Foundation ist completely missing. I am on my way to create it.
