### ISSUE TITLE
Example apps do not work locally

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1110]
examples/wrapper-components/react-javascript... 
npm install
npm run build:wrapper
npm run test:local

..and an error occurs. 

Tried: clean install

**Comment by verena-ifx** [comment]
this is fixed right @tishoyanchev ?

**Comment by tishoyanchev** [comment]
> this is fixed right @tishoyanchev ?

yes.

**Comment by tishoyanchev** [comment]
Fixed.
