### ISSUE TITLE
Enhancement: Update readme for Vue3 usage

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#1185]
Using Vue3 with Vite led to some warnings. This can be solved by setting a compiler option in vite.config.js
Update readme information accordingly:

```
plugins: [
vue({
template: {
compilerOptions: {
// treat all tags with a dash as custom elements
isCustomElement: (tag) => tag.includes('ifx-'),
},
},
}),
],
```

**Comment by tishoyanchev** [comment]
Updated in another Issue: https://github.com/Infineon/infineon-design-system-stencil/issues/1234
