### ISSUE TITLE
Inconsistency of search in Navbar Component

### ISSUE THREAD

**Issue by SteineSe100** [Infineon/infineon-design-system-stencil#1225]
Seeking to the search in navbar in Figma and to the navbar in the code component there is a incosistency available. Need to check and define it how it should be.

**Comment by SteineSe100** [comment]
> Seeking to the search in navbar in Figma and to the navbar in the code component there is a incosistency available. Need to check and define it how it should be.

**Comment by SteineSe100** [comment]
The detection here ment is related the search field in navbar which is visible everywhere in DDS FIGMA file and just the search icon in our navbar code component which leads to inconsistency. Sergej and Matthäus please look into this topic and define requirement, please. 
![Screenshot 2024-05-13 084522](https://github.com/Infineon/infineon-design-system-stencil/assets/45265314/753a05c6-82e4-4268-be01-dc75ba63c834)

**Comment by tishoyanchev** [comment]
@SteineSe100 
I already discussed with this Sergej and Matthaus, and we established the requirements. I've opened a new issue for it: https://github.com/Infineon/infineon-design-system-stencil/issues/1229
