### ISSUE TITLE
Tabs : active-tab-index not working properly

### ISSUE THREAD

**Issue by chaudharigau** [Infineon/infineon-design-system-stencil#1245]
active-tab-index property is not working as expected if value is set.
Please find below snap where the active-tab-index set to 2 and the expectation is that the tab c must be selected but irrespective of any index value tab A is selected.
Used Component version - 20.38.4
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/169887096/87ed222b-77d5-4664-bfe3-169f1be7802e)

**Comment by tishoyanchev** [comment]
@chaudharigau 
Hi, thanks for pointing out this issue. 
As it turns out, the active-tab-index had been removed from the Tabs component. 
We will now discuss whether to re-implement it, and then will let you know.
