### ISSUE TITLE
Alert: Close button not working

### ISSUE THREAD

**Issue by peter-dick** [Infineon/infineon-design-system-stencil#1246]
**Prerequisites**

Can you reproduce the problem reliably?
yes

Did you check current release notes for known issues?
yes

If this is not the latest release, have you checked newer releases? 
yes

**Description**:

The close button of the alert component has no function.

**Steps to Reproduce:**

1.  Open https://infineon.github.io/infineon-design-system-stencil/?path=/docs/components-alert--development
2. Click on "X" of alert

**Expected Result:**
Alert is closed or hidden in some form

**Actual Result:**
Nothing happens

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**
Latest

**Host OS and Version:**
Windows 10

**Comment by tishoyanchev** [comment]
Hi, @peter-dick 
Thanks for pointing this to us. We will investigate the issue and get pack to you.

**Comment by tishoyanchev** [comment]
@peter-dick 
Hello Peter,
Our DDS components do not come with an App-based functionality. 
We provide events, which developers can then use to create their App logic. 
The Alert component emits an event every time you click the "X" close button. What you do with that event is up to you. If you wish to hide the Alert on "X" close, you can use the event as an indicator when the button has been clicked, and then implement the logic to hide the component.
I will therefore now close this Issue. 
Let me know if you have further questions.
