### ISSUE TITLE
Multi-select: adjust design to Figma design

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1294]
When there are more options available than the number of selectable options, the rest of the options become 'disabled', and cannot be clicked, only hovered. The 'disabled' state is reflected in the checkbox only (reference below), the hover state stays the same. 

Also, design needs to be adjusted to the latest in Figma.

Refer to Figma for the new design: https://www.figma.com/design/SkRd14GjSqGbj08f45BkuZ/Explorations?node-id=972-29549&t=IvcUlVVqTIsxEmU7-0

Disabled state of the checkbox: https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=38242-6721&m=dev

**Comment by akashyeole** [comment]
@tishoyanchev 
Design for disabled state of option is not present in figma.

**Comment by tishoyanchev** [comment]
@akashyeole 
Is it more clear now?
