### ISSUE TITLE
CDN: allow user control over major version

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#1344]
Research/add versioning capability to the CDN

PS:
Only for a major version
Minor and Patch should come automatically

**Comment by tishoyanchev** [comment]
@verena-ifx 
I believe this works:
`<script type="module" src="https://cdn.jsdelivr.net/npm/@infineon/infineon-design-system-stencil@23/dist/infineon-design-system-stencil/infineon-design-system-stencil.esm.js"></script>`

I think this sets only the major version. Can you please test it to make sure?

**Comment by tishoyanchev** [comment]
not relevant anymore
