### ISSUE TITLE
Tabs: restore the active-tab-index functionality

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1359]
The Tabs component used to have an active-tab-index feature.
Currently, only the Prop name remains, but the logic and functionality is gone. 
Bring back or re-create the active-tab-index functionality again.

**Comment by pfafffabian-ifx** [comment]
Is there a reason why the line below is commented out?
It works if you just use the line

```ts
  componentWillLoad() {
    this.internalOrientation = this.orientation.toLowerCase() === 'vertical' ? 'vertical' : 'horizontal';
    if (this.internalActiveTabIndex !== this.activeTabIndex) {
      this.ifxTabChange.emit({ previousTab: this.internalActiveTabIndex, currentTab: this.activeTabIndex });
    };
    // this.internalActiveTabIndex = this.activeTabIndex;
    this.internalFocusedTabIndex = this.internalActiveTabIndex;
    this.updateTabStyles();
    this.onSlotChange();
  }
```

**Comment by tishoyanchev** [comment]
> Is there a reason why the line below is commented out? It works if you just use the line
> 
> ```ts
>   componentWillLoad() {
>     this.internalOrientation = this.orientation.toLowerCase() === 'vertical' ? 'vertical' : 'horizontal';
>     if (this.internalActiveTabIndex !== this.activeTabIndex) {
>       this.ifxTabChange.emit({ previousTab: this.internalActiveTabIndex, currentTab: this.activeTabIndex });
>     };
>     // this.internalActiveTabIndex = this.activeTabIndex;
>     this.internalFocusedTabIndex = this.internalActiveTabIndex;
>     this.updateTabStyles();
>     this.onSlotChange();
>   }
> ```

Likely a mistake. Good find 👍
