### ISSUE TITLE
Table: not reactive with vue3 + options api

### ISSUE THREAD

**Issue by peter-dick** [Infineon/infineon-design-system-stencil#1369]
**Prerequisites**

Can you reproduce the problem reliably?
yes

Did you check current release notes for known issues?
yes

If this is not the latest release, have you checked newer releases? 
yes

**Description**:

When using ifx-table with dynamic data, which is based on current filter (ifx-search-field) and changes reactively, is not reflected in the table component. In Vue debug tools it is visible that the row data is updated, however this is not reflected in the ifx-table, which binds that row data.

Use the attached code example to reproduce the issue.
[vue3-ifx-table.zip](https://github.com/user-attachments/files/16279005/vue3-ifx-table.zip)

**Actual behavior**:
When entering "Project 1" in search field, the projects are filtered and the underlying data is changed. However the table remains unchanged.

**Expected behavior**:
When entering "Project 1" in search field, the projects are filtered and the underlying data is changed. That data is also rendered by ifx-table component.

**Comment by tishoyanchev** [comment]
@peter-dick 
Hi,
Yes, we are aware of this. At the moment, dynamic rendering of the data is not possible for the basic-table component.

**Comment by peter-dick** [comment]
We are using the advanced table (`ifx-table`, not `ifx-table-basic`) which also does not support dynamic rendering. Any update regarding when you intend to support it? And if not, any suggested way to force/trigger rerender when used in conjunction with vue3?

**Comment by tishoyanchev** [comment]
@peter-dick 
I can't tell at the moment when will we provide the dynamic rendering of the basic-table. 
I can't give you any good suggestions because I am not an expect in Vue. I would assume using the key attribute with the v-for, but I can't be sure.

**Comment by pfafffabian-ifx** [comment]
> We are using the advanced table (`ifx-table`, not `ifx-table-basic`) which also does not support dynamic rendering. Any update regarding when you intend to support it? And if not, any suggested way to force/trigger rerender when used in conjunction with vue3?

You can force rerendering by using the :key attribute.
For example in your code:
```
    <ifx-table
      row-height="compact"
      pagination="true"
      :pagination-page-size="perPage"
      :cols="JSON.stringify(tableColumns)"
      :rows="JSON.stringify(tableData)"
      :key="JSON.stringify(tableData)"
    ></ifx-table>
```

**Comment by peter-dick** [comment]
> > We are using the advanced table (`ifx-table`, not `ifx-table-basic`) which also does not support dynamic rendering. Any update regarding when you intend to support it? And if not, any suggested way to force/trigger rerender when used in conjunction with vue3?
> 
> You can force rerendering by using the :key attribute. For example in your code:
> 
> ```
>     <ifx-table
>       row-height="compact"
>       pagination="true"
>       :pagination-page-size="perPage"
>       :cols="JSON.stringify(tableColumns)"
>       :rows="JSON.stringify(tableData)"
>       :key="JSON.stringify(tableData)"
>     ></ifx-table>
> ```

Thanks for the tip Fabian, the workaround with the key works!
