### ISSUE TITLE
Footer: Add support for contact and cookie management links

### ISSUE THREAD

**Issue by peter-dick** [Infineon/infineon-design-system-stencil#1403]
**Is your feature request related to a problem? Please describe.**

We have a requirement (vue3) to provide links in the footer for **Contact** and **Management of cookies**.
These can be seen in the current footer at [https://softwaretools.infineon.com/](https://softwaretools.infineon.com/)

**Describe the solution you'd like**

Add attributes for `ifx-footer` component, to support the display of the additional two fields above.
Suggested fields to be added: `contactUrl`, `contactTarget`, `cookieManagementUrl`, `cookieManagementTarget`.

**Describe alternatives you've considered**

Alternatively, provide a slot, where further links can be added.

**Comment by peter-dick** [comment]
Is there an ETA for the enhancement to be implemented? Currently we require the additional fields to incorporate the new footer in IDCO.

**Comment by tishoyanchev** [comment]
@peter-dick 
> Is there an ETA for the enhancement to be implemented? Currently we require the additional fields to incorporate the new footer in IDCO.

This is a high priority task, but it's also a big one, and we would implement it incrementally in the comings weeks and months.

**Comment by tishoyanchev** [comment]
Issue has been re-created: https://github.com/Infineon/infineon-design-system-stencil/issues/1438
