### ISSUE TITLE
Toast Notifications feature

### ISSUE THREAD

**Issue by peter-dick** [Infineon/infineon-design-system-stencil#1409]
Implement a Toast notification component, which allows the push of one or more toast messages, giving the user feedback for certain actions. The toast notification should be distinguishable between different types: info, warning and error.
Additionally, it should be possible to customize certain aspects of the toast notification:
* text: custom title and message (dynamic content via slots)
* duration: allow to customize the display duration of toast notifications, with options ranging from a few seconds to until dismissed by the user.
* ability to close / dismiss the toast notification 
* ability to show multiple toast notifications (sorted by the time they are pushed)

### Use-cases
* Visual feedback on failed operations / successful actions / system errors

### Examples

![image](https://github.com/user-attachments/assets/0dd1638a-559a-429b-9ec6-a811db8a0559)

![image](https://github.com/user-attachments/assets/fa2f3c30-af0c-47d3-9273-bcb414f452aa)

![image](https://github.com/user-attachments/assets/67159fa1-7fb8-4475-bdcc-455215c4bc0b)

**Comment by tishoyanchev** [comment]
@peter-dick 
Hi, 
We have decided that the use-case is too specific, and does not warrant an implementation of this component. Please use the ifx-alert component for your use case.
