### ISSUE TITLE
Research: Process + Example documentation for Storybook

### ISSUE THREAD

**Issue by g-rdknt** [Infineon/infineon-design-system-stencil#145]
Aim: estabish a process how to publish documentation to Storybook for Radikant

**Comment by verena-ifx** [comment]
Update after migrating to Storybook v7:

- an .mdx file needs to be created within the folder of the component that documentation should be added to
- the .stories.ts file (created by the developers) needs to be updated with an import statement of the .mdx file and the parameters specifying that the docs page should be created based on the .mdx file
