### ISSUE TITLE
Bug: Searchfield applies parent background color inconsistently

### ISSUE THREAD

**Issue by peter-dick** [Infineon/infineon-design-system-stencil#1504]
If the searchfield component (used with vue3) is placed in a container with any other background color than white, the background color is applied on the searchfield's inner area (search-field__wrapper), which make it look unappropriate:

![image](https://github.com/user-attachments/assets/9ac08cda-d207-4dac-a109-f30f97d15524)

The expected behavior is, that the component remains white:
![image](https://github.com/user-attachments/assets/24a7bbdf-c35a-469b-b682-855a3e4cb21e)

**Comment by tishoyanchev** [comment]
@peter-dick 
Issue is resolved.
