### ISSUE TITLE
Storybook: investigate the possibility of adding tabs to each story page for different frameworks 

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1521]
Investigate the possibility of adding tabs for every framework  - react/vue/angular/vanilla for every story page

**Comment by akashyeole** [comment]
@tishoyanchev 
Checkout this storybook - https://uikit.wfp.org/docs/index.html?path=/docs/components-ui-elements-notification-legacy--regular there is 'react' and 'html' options for source code.
We can also implement something like this.

**Comment by tishoyanchev** [comment]
Continued here: https://github.com/Infineon/infineon-design-system-stencil/issues/1531
