### ISSUE TITLE
Find an alternative to cpx, as it has some deprecated dependencies

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#1538]
cpx uses an old version of babel/runtime, which in turn uses an outdated version of core-js.
Investigate if we can use another library for our copy tasks, that runs on both linux and windows machines

**Comment by akashyeole** [comment]
@verena-ifx 
I found ncp as an alternative to cpx.
Check out this PR- https://github.com/Infineon/infineon-design-system-stencil/pull/1544
https://www.npmjs.com/package/ncp
