### ISSUE TITLE
Enhancement: Add selected tab property to content-switcher component

### ISSUE THREAD

**Issue by peter-dick** [Infineon/infineon-design-system-stencil#1565]
### Detailed description of what you want to happen

Currently it is not possible to set a content switcher tab as active from code but only react on changed item selection via ifxChange event.

I want to have the ability to set the active index / tab, that shall be active when the component is loaded.

### Upload a screenshot or reference an example if possible

E.g. a certain tab, like the table view in the screenshot below shall be preselected.

![image](https://github.com/user-attachments/assets/66d15a9b-8497-4467-8799-516cd670d0a2)

### Why do you need this feature?

We use the content switcher to allow the user to switch between different views (table / list). This setting is persisted and when the user loads the view again, the previously persisted setting is loaded and shall be active.

### Do you have a deadline?

No

### Additional information
Add a prop for setting the default value on load time

**Comment by tishoyanchev** [comment]
Your Issue has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!

**Comment by akashyeole** [comment]
@tishoyanchev @peter-dick 
Upon checking I found that, `selected` prop can be used on `<ifx-content-switcher-item>` to set an item active by default.
Eg:
  ```
<ifx-content-switcher-item selected='true' value="item-1">
     <ifx-icon icon="applications-16"></ifx-icon>Item 1
</ifx-content-switcher-item>
  ```

**Comment by tishoyanchev** [comment]
> @tishoyanchev @peter-dick Upon checking I found that, `selected` prop can be used on `<ifx-content-switcher-item>` to set an item active by default. Eg:
> 
> ```
> <ifx-content-switcher-item selected='true' value="item-1">
>    <ifx-icon icon="applications-16"></ifx-icon>Item 1
> </ifx-content-switcher-item>
> ```

@peter-dick 
Would this solution suffice?

**Comment by tishoyanchev** [comment]
@peter-dick 
If the above offered solution does not work for you, please re-open the issue again, or create a new one with the solution you would like you see.
