### ISSUE TITLE
New Component: Just a test

### ISSUE THREAD

**Issue by SteineSe100** [Infineon/infineon-design-system-stencil#1575]
### Detailed description of the component, its design and behavior

Test

### Do you plan to use this component for web applications, mobile or both?

Test

### Upload a screenshot or reference an example if possible

Test

### Why do you need this component?

Test

### Do you have a deadline?

Test

### What project is this component for?

Test

### Additional information

Test

**Comment by tishoyanchev** [comment]
Your Issue has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!
