### ISSUE TITLE
Slider: Possibility to disable only one side of the range slider

### ISSUE THREAD

**Issue by GjJoana** [Infineon/infineon-design-system-stencil#1596]
### Detailed description of what you want to happen

Would be nice to have the possibility that instead of disabling the whole slider, to be able to only partially disable (one or the other side) of the range slider.

### Why do you need this feature?

Customer request. Depending on some calculations, sometimes the minimum value of a range slider should not be editable from the user, and in other cases it should, so it would be nice to have this feature available in the dds component

### Do you have a deadline?

End of December.

**Comment by tishoyanchev** [comment]
@GjJoana 
Hello, thank you for the request. 
Could using a single handle with min and max values not work for you?
What is the use-case that requires disabling one of the handles?

**Comment by GjJoana** [comment]
@tishoyanchev 
Hello,

We have a use case that requires obtaining a range of values from the user, which involves two inputs.
Depending on another input (such as a checkbox), the minimum and maximum values of the range slider can be selectively disabled. One possible solution would be to hide the range slider and replace it with a single slider (with minimum and maximum values) when the checkbox status changes. However, we believe that allowing the option to disable only one of the handles would maintain a more consistent user interface and provide a better user experience.

**Comment by tishoyanchev** [comment]
@GjJoana 
Hello, 
Sorry for the late response. 
We had an internal meeting yesterday, and we discussed your request again, but the designers said it would not be consistent with user expectations to be able to disable only one of the handles. It only adds unnecessary complexity to the component. I'm sorry to say they decided against your request. 
For that reason, I will now close this issue. 
Please feel free to open another issue if necessary.
