### ISSUE TITLE
single select: delete button does not show up on load

### ISSUE THREAD

**Issue by ralfongit** [Infineon/infineon-design-system-stencil#1617]
### Detailed description of how to reproduce the problem

refers to: https://github.com/Infineon/infineon-design-system-stencil/issues/1563

If one option is already selected on load of the single-select, the x (delete) does not show up.
Only if you open the dropdown and select an option by clicking on it, the x (delete) button shows up.

### Upload a screenshot

![image](https://github.com/user-attachments/assets/d4624b8b-bf4d-498e-a426-cf0ac84f68b0)

### Expected behavior

If an option is selected (has selected: true), the x (delete) button should be shown.

**Comment by tishoyanchev** [comment]
Your [issue](https://github.com/orgs/Infineon/projects/4?pane=issue&itemId=89659004&issue=Infineon%7Cinfineon-design-system-stencil%7C1617) has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!

**Comment by tishoyanchev** [comment]
Resolved in another PR
