### ISSUE TITLE
Component-name: Dropdown

### ISSUE THREAD

**Issue by ajaygonepuri** [Infineon/infineon-design-system-stencil#1618]
### Detailed description of what you want to happen

Increase or Decrease the width of Dropdown component
Add or Remove Hovering on Dropdown component
Change color of text and border in Dropdown component

### Why do you need this feature?

Need this to match the Design given for my Project

### Do you have a deadline?

Deadline is Tomorrow

### Additional information

Suggestion: the dropdown should stretch to fill the parent

**Comment by tishoyanchev** [comment]
@ajaygonepuri 
Hi, thank you for your submission. 
Our DDS components are based on Infineon design and branding theme, and the colors/fonts and other design theming should not be changed as it is already brand compliant. 
Besides that, we do not provide a way at the moment for developers to customize styling or functionality.
