### ISSUE TITLE
IFX-Stepper: Show content between steps and short text information on the left hand side

### ISSUE THREAD

**Issue by UgurAyvaz** [Infineon/infineon-design-system-stencil#1624]
### Detailed description of what you want to happen

1. We would like to have content between the individual steps (see screenshot). Currently, content can only be on the left or right hand side of the stepper but not in between of the steps.

2. We would like to  have the option to place short text on the left hand side of stepper's status icons (see screenshot).  

### Upload a screenshot or reference an example if possible

![image](https://github.com/user-attachments/assets/88181820-33aa-4ffb-90aa-d949cbe481b0)

### Why do you need this feature?

It is predetermined in the Figma templates of Infineon. 

### Do you have a deadline?

As soon as possible, it is urgent.

**Comment by UgurAyvaz** [comment]
Hi, here is the link https://www.figma.com/design/IbFyAFXTfnOdKrxBCNWQqm/IDC-Online---Main-Design?node-id=200-4000&node-type=frame&t=rEeVKP3Dt6yqssve-0

**Comment by SergejLust** [comment]
@UgurAyvaz Hello Ugur Ayvas, in order not to disappoint your users and still offer them something that works and is understandable, you can use our vertical stepper. However, this is not based on your stepper's interactive logic. But the idea is the same. I also created some quick mockups that maybe could help you and make understand how our stepper would look like in your context. We also recommend to user shorter labels for the steps (also shown in the mockup). I hope this helps you to implement a different looking and working stepper.
[vertical-stepper.zip](https://github.com/user-attachments/files/18062565/vertical-stepper.zip)
