### ISSUE TITLE
IFX-Table: Selectable Text

### ISSUE THREAD

**Issue by MichaelHolley** [Infineon/infineon-design-system-stencil#1628]
### Detailed description of what you want to happen

Allow the selection of text in table columns via `enableCellTextSelection ` options property.

### Why do you need this feature?

Selecting text and copying is very usefull for sharing with others and other interaction.

### Do you have a deadline?

no

### Additional information

ag-grid provides the option `enableCellTextSelection` [see here](https://www.ag-grid.com/javascript-data-grid/cell-text-selection/)

**Comment by tishoyanchev** [comment]
Your [issue](https://github.com/orgs/Infineon/projects/4/views/1?pane=issue&itemId=90675124&issue=Infineon%7Cinfineon-design-system-stencil%7C1628) has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!
