### ISSUE TITLE
Pagination: After selection values can be removed from dropdown resulting in weird behavior

### ISSUE THREAD

**Issue by weisserIFX** [Infineon/infineon-design-system-stencil#1634]
### Detailed description of how to reproduce the problem

Change the results per page option for the pagination component.
New selected value will have an X option next to it. (Which is probably not expected)
After removing a value, no value is shown in dropdown.

### Upload a screenshot

![pagination bug](https://github.com/user-attachments/assets/00fbc671-a6fe-4ff7-accd-2be2ccd8de11)

### Describe the development framework

DDS version 29.1.0
Vue 3.4 Migration build

### Expected behavior

Drop down for results should not allow for values to be removed as there should always be one option selected.

**Comment by tishoyanchev** [comment]
@weisserIFX 
Hi, thank you for your submission. 
There is already an issue created for this bug.
https://github.com/Infineon/infineon-design-system-stencil/issues/1615
