### ISSUE TITLE
Single-select: clear field when options change

### ISSUE THREAD

**Issue by ralfongit** [Infineon/infineon-design-system-stencil#1654]
### Detailed description of how to reproduce the problem

I have an options array for single-select.
single-select shows the options correctly and user select one option.
single-select is closed and through other activity the options array of the single-select gets reloaded.
The new options array does not contain the previously selected option but totally different ones and all have selected: false.
But single-select still shows the previously selected option.

### Upload a screenshot

1. 
![image](https://github.com/user-attachments/assets/05ebe72d-9888-47ef-852e-30dd3f9eb04c)

2. 
![image](https://github.com/user-attachments/assets/5b4775e6-0f74-482b-b920-64d68956c8b3)

### Describe the development framework

VueJs 3
DDS version 30.4.0

### Expected behavior

single-select should in this case clean the shown value (selected option)

**Comment by tishoyanchev** [comment]
Your [issue](https://github.com/orgs/Infineon/projects/4/views/1?pane=issue&itemId=90821181&issue=Infineon%7Cinfineon-design-system-stencil%7C1654) has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!

**Comment by ralfongit** [comment]
That was quick :)
Thank you!
