### ISSUE TITLE
Evaluate Possibility of Ignoring Auto-Generated Files in Git

### ISSUE THREAD

**Issue by kaiwerther** [Infineon/infineon-design-system-stencil#166]
### Description:
Our digital design system currently includes automatically generated files for Stencil (the component.ts files) and the wrapper files for Vue/React, which are under source control. This issue aims to evaluate whether these files can be added to .gitignore and removed from the GitHub repository without causing any disruptions or breaking anything in our system.
### Acceptance Criteria:
Conduct a feasibility study on ignoring these automatically generated files in git.
If feasible, add these files to .gitignore and remove them from the GitHub repository.
Test extensively to ensure that the system still works as expected after these changes.
Update any relevant documentation or workflows that reference these files.
### Additional Information:
This was identified during a code review of our system. Ignoring these files could potentially declutter our repository and streamline our source control process. Please reach out if more information or clarification is needed.

**Comment by tishoyanchev** [comment]
@verena-ifx  Is this issue still relevant?

**Comment by benedikt-ifx** [comment]
All files that can be ignored are included in the .gitignore already. Please create a new issue if there are any specific suggestions.
