### ISSUE TITLE
Content-Switcher: Enable Default Option

### ISSUE THREAD

**Issue by VishnuDeepak11** [Infineon/infineon-design-system-stencil#1660]
### Detailed description of what you want to happen

Currently the content Switcher lets the user selects one of the option without any preselection, but we would like to have an input in content switcher component to let the component know the default option and that is being preselected without any user inputs 

### Upload a screenshot or reference an example if possible

AS-IS (by default)

<img width="295" alt="image" src="https://github.com/user-attachments/assets/9343b68f-1467-4501-bef3-bf57de9795ce" />

To-BE (by default)

<img width="377" alt="image" src="https://github.com/user-attachments/assets/1bc29a71-9a5b-4c54-a2ab-51615cd873ee" />

### Why do you need this feature?

For Project Requirements

### Do you have a deadline?

Would be nice to have feature by next month end if possible

**Comment by tishoyanchev** [comment]
@VishnuDeepak11 
Hi, 
This is already possible with the `selected` prop.
`<ifx-content-switcher-item selected="true" value="item-1">`
