### ISSUE TITLE
Rework of dropdown menu component and split into two (select + dropdown)

### ISSUE THREAD

**Issue by kaiwerther** [Infineon/infineon-design-system-stencil#177]
Currently, our application uses a single dropdown component that combines the select and dropdown menu functionality. This combination may create a confusing user experience and might also limit the functionality of both select and dropdown components. We aim to separate these components for better clarity and enhanced user experience.

**Comment by mattradikant** [comment]
Needs to be finished first.
Incorporated with the latest version of master branch.
