### ISSUE TITLE
Struture Angular + Vanillajs example applications in a similar manner as Vue + React

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#241]
Struture Angular + Vanillajs example applications in a similar manner as Vue + React.
Currently all the components are in one file. To reduce complexity, a folder structure should be established for each component displayed in the example application

**Comment by verena-ifx** [comment]
https://github.com/Infineon/infineon-design-system-stencil/issues/319

**Comment by tishoyanchev** [comment]
@verena-ifx  Is this tasks the same as #319 ?
