### ISSUE TITLE
Implementation: Templates for React + Vue + Angular

### ISSUE THREAD

**Issue by mattradikant** [Infineon/infineon-design-system-stencil#248]
Templates for basic application page with exemplary designs

[Strong branding](https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=7640-5436&mode=design)
[Modest branding](https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=7640-6597&mode=design)
[Subtle branding](https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=7640-6598&mode=design)

**Comment by benedikt-ifx** [comment]
Closed as duplicate
