### ISSUE TITLE
Design Review: Component - Alerts

### ISSUE THREAD

**Issue by vavan-s** [Infineon/infineon-design-system-stencil#255]
**Component Name:** Alerts

**Issue 1:**

- Description: Wrong component height
- Steps to Reproduce: Inspect the height of the Alert component in StoryBook.
- Expected Result: Alert component height 48px.
- Actual Result: Alert component height 49px

- Screenshot of the Actual State:
<img width="1751" alt="Screenshot 2023-07-13 at 16 15 00" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/0deb9829-503b-42dd-91a7-dabfa2d99ec2">

**Issue 2:**

- Description: Unnecessary component state variant
- Steps to Reproduce: Inspect the component state variants
- Expected Result: State variants - Primary, Success, Warning, Danger
- Actual Result: State variants - Primary, Secondary, Success, Warning, Danger

- Screenshot of the Actual State:
<img width="679" alt="Screenshot 2023-07-17 at 16 18 14" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/469c4901-3891-460c-a5fa-021bfb2c43f0">

- Screenshot of the Expected Result:
<img width="536" alt="Screenshot 2023-07-13 at 16 17 54" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/d036816f-88da-4407-bcd2-19614443647f">
e link]

**Additional issue**

- Description: Missing component state variant
- Steps to Reproduce: Inspect the component state variants in the Figma file
- Expected Result: State variants - Primary, Success, Warning, Danger, Additional information
- Actual Result: State variants - Primary, Secondary, Success, Warning, Danger

- Figma Reference Link: https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/branch/VxG1MQaNdzsjiW6P6WmVt9/Infineon-DDS-%7C-Main?type=design&node-id=19446%3A13846&mode=design&t=D9W85aXjy3oCU66i-1

We are happy to help via quick chat/huddle/webex for any questions & details if necessary

**Comment by verena-ifx** [comment]
Hi @vavan-s 
the report writing looks great. Only thing I would change is the title. Let's just call it Design Review: Component-name (we dont really need the "StoryBook" in the beginning.
The rest looks good. Since we are still waiting for the updated tokens, I would take a look at this, once we have those or what do you think @tishoyanchev ?

**Comment by vavan-s** [comment]
Hi @verena-ifx

Ok, super, thanks for the info. I'll update the titles and continue posting the issues for other components. 

Thanks

**Comment by tishoyanchev** [comment]
> Hi @vavan-s the report writing looks great. Only thing I would change is the title. Let's just call it Design Review: Component-name (we dont really need the "StoryBook" in the beginning. The rest looks good. Since we are still waiting for the updated tokens, I would take a look at this, once we have those or what do you think @tishoyanchev ?

@verena-ifx @vavan-s 
Yeah, for the issues related to colors, it makes sense to wait for the new tokens, but the other issues, we can look at them now.
A few notes on my side about the review:
1) Can you maybe change "Screenshot/reference" to "Screenshot/reference of expected result" so it's clear what the image represents. 
2) About Issue 4. By "outline", do you mean "border"? The component does not have outline.

**Comment by vavan-s** [comment]
@tishoyanchev @verena-ifx 

Hey Tisho, 
Thanks for the update related to colors. I'll write the issues regarding colors anyway but you don't have to do anything until you get new tokens. 

No problem, I can adress the Screenshot/Reference only to expected result. This means that I will post a Figma reference link of the component always. Besides the Figma link, I can also provide an exact screenshot of the issue, or it's enough to post the Figma link only? Let me know and I'll adjust the issues I posted. 

Regarding the issue 4, yes, I meant the "border". 

Thanks :)

**Comment by tishoyanchev** [comment]
@vavan-s 
> I can adress the Screenshot/Reference only to expected result.

My point was that in the above image, it wasn't clear if the Reference/Screenshot is showing the issue or the expected result. So, when you are adding a reference, make sure you clarify if this is the expected outcome, or the current issue.

> I can also provide an exact screenshot of the issue, or it's enough to post the Figma link only?
Screenshot with the expected result would be useful.

**Comment by vavan-s** [comment]
@tishoyanchev 

I've updated the content on this issue right now. You can check it out and let me know if this would work better. 

For some components it makes sense to show only a screenshot of the current state, and for others, both current state and expected result. This is why I will always write what is the screenshot representing. 

For an example, two screenshots for 1px height adjustment wouldn't make much sense because visually they would look the same.
