### ISSUE TITLE
Design Review: Component - Badge

### ISSUE THREAD

**Issue by vavan-s** [Infineon/infineon-design-system-stencil#260]
**Component Name: Badge**

**Issue 1:**

- Description: Add a badge with icon variant
- Steps to Reproduce: Check the available badge variants in Figma
- Expected Result: A badge with icon variant included in StoryBook
- Actual Result: A badge with icon variant is excluded in StoryBook

- Screenshot of Expected Result: 
<img width="462" alt="Screenshot 2023-07-14 at 16 14 06" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/91cfab44-818b-49e1-b750-127296b4e0df">

- Figma Reference Link:
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=23904%3A14546&mode=design&t=3no3fMzu06vmnQ6I-1

**Comment by tishoyanchev** [comment]
For version 2.
