### ISSUE TITLE
Design Review: Component - Navbar

### ISSUE THREAD

**Issue by vavan-s** [Infineon/infineon-design-system-stencil#283]
**Component Name: Navbar**

**Issue 1:**

- Description: Logo variants missing
- Steps to Reproduce: Inspect the Navbar component
- Expected Result: Ability to choose defined logo variants in the Navbar 
- Actual Result: No ability to choose defined logo variants in the Navbar

- Screenshot of Actual Result:
<img width="939" alt="Screenshot 2023-07-19 at 14 20 58" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/8a94cfef-1865-45c6-a8ee-c6d06ace27de">

- Screenshot of Expected Result: 
<img width="632" alt="Screenshot 2023-07-19 at 14 58 14" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/221c3f40-cb04-4810-9a72-91e757636bd0">

- Figma Reference Link: 
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=19241%3A12484&mode=design&t=MQEvoxaoZLhFxEZs-1

**Issue 2:**

- Description: Add Vertical and Horizontal sidebar
- Steps to Reproduce: Inspect the Navbar component
- Expected Result: Vertical and Horizontal sidebar orientation
- Actual Result: No Vertical and Horizontal sidebar orientation

- Screenshot of Expected Result:
<img width="550" alt="Screenshot 2023-07-19 at 14 33 23" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/f48eb84f-4d61-4ccd-be76-3cd00e85b3c0">

- Figma Reference Link: 
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=19241%3A12529&mode=design&t=MQEvoxaoZLhFxEZs-1

**Issue 3:**

- Description: Responsive behaviour
- Steps to Reproduce: Inspect the Navbarn component responsivness
- Expected Result: 5 Breakpoint variants in responsive behaviour
- Actual Result: No breakpoint variants in responsive behaviour

- Screenshot of Expected Result:
<img width="668" alt="Screenshot 2023-07-19 at 14 38 38" src="https://github.com/Infineon/infineon-design-system-stencil/assets/139236169/4f562b59-77bf-4c7c-80da-0c643244af65">

- Figma reference link:
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=19241%3A12529&mode=design&t=MQEvoxaoZLhFxEZs-1

**Issue 4:**

- Description: Add Navigation item variants
- Steps to Reproduce: Inspect the Navigation component
- Expected Result: Ability to choose defined navigation item variants
- Actual Result: No ability to choose defined navigation item variants

- Figma Reference Link:
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=19241%3A12392&mode=design&t=MQEvoxaoZLhFxEZs-1

**Additional issue:**

- Description: Mobile menu
- Steps to Reproduce: Inspect the Mobile menu in Figma
- Expected Result: Mobile menu in StoryBook
- Actual Resutl: Mobile menu not in StoryBook

- Figma Reference Link:
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=23003%3A13742&mode=design&t=MQEvoxaoZLhFxEZs-1

**Comment by tishoyanchev** [comment]
All issues are for v-2 of the navbar.
