### ISSUE TITLE
Implement filter feature on the Dropdown taking the emitted value from the Search-field component

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#354]
The search-field component needs to have a filter feature when it's nested inside the dropdown component. Note: the filter feature may not be imbedded in the search-field component itself, but enabled/implemented only for the dropdown component.

**Comment by verena-ifx** [comment]
as we discussed yesterday, the search-field itself does not need a Filter function. the search-field already emits an event with the search-term. This term can then be processed by whoever needs it. But the search-field does not have any input to filter
