### ISSUE TITLE
Update search-bar in the Navbar

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#356]
When opened, the search-bar must take 100% of the Navbar width.

**Comment by verena-ifx** [comment]
that should already be the case though, no? at least when you add the search-bar to one of the example apps, it already takes the full width. not sure about the behavior, when embedded of course.

**Comment by tishoyanchev** [comment]
That's not what I meant :D 
I meant to say that when you open the search-bar inside the Navbar, the search-bar must stretch from one end of the Navbar to the other, hiding all the other existing menu-items.

**Comment by verena-ifx** [comment]
whats the status of this? @tishoyanchev
