### ISSUE TITLE
Select: the arrow issue

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#417]
When you click on the single select field, the components gets focused, the list opens, and the arrow moves down. When you click again, the list closes, but the component stays focused, and the arrow does not move back to pointing down. 

Fix: the arrow should move back to pointing down when the list closes. The arrow must be tied to the list opening and closing, not whether the component is focused or not.

**Comment by verena-ifx** [comment]
this is also fixed already
