### ISSUE TITLE
Select: the focusable issue

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#419]
When you select an option from the single-select list, the list closes, but the component stays focused, and when you click again on the options to open the list, the component then gets unfocused, so you have to click again to focus and open the list again.

Fix: As already mentioned in the previous Select issue, the opening/closing of the List must not be bound to whether the component is focused or not. When you select an option, the component must become not focused, so clicking on it again must open the list.

**Comment by verena-ifx** [comment]
that is fixed already
