### ISSUE TITLE
Pagination: future feature

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#441]
Currently, the nested Select component has 10/20/30 fixed values, which are used for setting the per-page option. 
Consider the possibility of using an algorithm for automatically determining the per-page option values.

**Comment by MichaelHolley** [comment]
There is multiple use-cases for this improved pagination-component within multiple of our internal applications, which would make this a big improvement.

I think giving the developer the freedom to pass in n-amount of numbers would be a much greater benefit than replacing it with a automatic system.

To give further feedback - best suited would be to:
- pass an array of n-amount of elements as a property e.g. [10, 20, 50, 100, ...]
- have a property to include a "all"-option within the select

**Comment by MichaelHolley** [comment]
@tishoyanchev Why has this been moved to "Released" and the issue been closed? I can't find neither related branches, PRs nor mentions in any release.
We were looking forward to use this feature, because setting the items-per-page dropdown values would allow us to replace our own implementation of the component, as we are dependant to set other values than [10, 20, 30].

**Comment by tishoyanchev** [comment]
> @tishoyanchev Why has this been moved to "Released" and the issue been closed? I can't find neither related branches, PRs nor mentions in any release. We were looking forward to use this feature, because setting the items-per-page dropdown values would allow us to replace our own implementation of the component, as we are required to set other values than [10, 20, 30].

Hi, 
I closed the issue because there was no internal consensus on this issue. 
Since you are requesting to give the user the option to set the items per page option, I will discuss this internally and if agreed upon, I will open up another issue for it. But I can say even now that it sounds reasonable to me.
