### ISSUE TITLE
Multi Select component: small issues

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#445]
When **max-item-count** is **1**, there are several issues:
1. When you click on an option that has nested options, all nested options get selected
2. When you click on one of the nested options, the sibling nested options get selected too
3. Once an option has been selected, clicking on a non-nested option will highlight the option item in the wrong color. The highlight background-color and the checkbox border have currently the same color, so checkbox becomes undistinguishable. The background-color on an active option item (once clicked, not pressed) and the checkbox border color should not be the same. Check figma for reference. Also see image reference:

![Image](https://github.com/Infineon/infineon-design-system-stencil/assets/108734092/a301201b-3239-4c2f-94a9-0236d6fb35ec)

**Comment by verena-ifx** [comment]
> 1. k on an option that has nested options, all nested options get selected

thats how it should be though. If the parent is selected, it gets selected together with the child elements

**Comment by verena-ifx** [comment]
> 2\. When you click on one of the nested options, the sibling nested options get selected too

can you demonstrate that? I do not see that issue

**Comment by verena-ifx** [comment]
> 3\. Once an option has been selected, clicking on a non-nested option will highlight the option item in the wrong color. The highlight background-color and the checkbox border have currently the same color, so checkbox becomes undistinguishable. The background-color on an active option item (once clicked, not pressed) and the checkbox border color should not be the same. Check figma for reference. Also see image reference:

this one, ill take a look at. it occurs once the max-item count is lower then the available items

**Comment by tishoyanchev** [comment]
> > 2. When you click on one of the nested options, the sibling nested options get selected too
> 
> can you demonstrate that? I do not see that issue

Yes, just select the max-item-count="1", and then select one of the sub-options. 
Note: I meant to say that the sibling is selectable. It does not get selected automatically.

**Comment by verena-ifx** [comment]
> t the sibling is selectable. It does n

ah yes (Y)
