### ISSUE TITLE
Select: update focus state

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#446]
The focus state is an 2px outline with a 2px offset, e.g.: 
outline: tokens.$ifxColorOcean500 solid tokens.$ifxSize25;
outline-offset: tokens.$ifxSpace25;

**Comment by benedikt-ifx** [comment]
The focus state is an 2px outline with a 2px offset, e.g.:

outline: tokens.$ifxColorOcean500 solid tokens.$ifxSize25;
outline-offset: tokens.$ifxSpace25;
