### ISSUE TITLE
Breadcrumbs: cannot run on vue-javascript/typescript and angular

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#463]
The 442-breadcrumbs-dropdown-menu-needs-to-be-updated PR cannot run on some of the example apps: vue-javascript, vue-typescript and angular. It runs on react-javascript, react-typescript and vanilla-cdn.

**Comment by verena-ifx** [comment]
fixed in PR https://github.com/Infineon/infineon-design-system-stencil/pull/453
