### ISSUE TITLE
Modal: v-2

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#527]
Due to missing design requirements, it is unclear whether a long text should expand the Modal height, or introduce a scroll-bar. 
Currently, the text is limited to 1 line with ellipsis.
Align with designers what should be the expected behavior when long text is added.

**Comment by MichaelHolley** [comment]
Limiting the modal to one-line content is pretty restrictive.
Improving this behavior, would be much appreciated as it would allow us to provide more information.
