### ISSUE TITLE
Tooltip: customizable size

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#592]
The tooltip currently uses a library, and many of the styled applied to the tooltip come from pre-defined classes, one of which is the position: absolute on the main container, which makes it difficult to let the width adjust to content. For that reason, setting up custom pre-defined sizes might be a good solution.

**Comment by verena-ifx** [comment]
@tishoyanchev the tooltip should definitely use a library. sizes currently are as they are defined in the design.
