### ISSUE TITLE
Migration of MyInfineon Stencil components into the DDS

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#607]
MyInfineon has developed several own Stencil components, spread across 3 repositories. Since the project will stop in a few months, we can potentially migrate some of their components into the DDS.
After a first alignment, there are definitely a few components that could benefit us.

**Priority**: low (current focus = bugfixes, support of users)

**Next Steps:**
- Discussion of the components with our designers
- Definition of which components will be migrated
- Resource planning

**Comment by tishoyanchev** [comment]
@verena-ifx  
Can you provide a link?

**Comment by tishoyanchev** [comment]
Not relevant anymore
