### ISSUE TITLE
Button: Reset-button in form triggers submit

### ISSUE THREAD

**Issue by MichaelHolley** [Infineon/infineon-design-system-stencil#626]
I am unable to provide two buttons in a `<form />`-Tag like a Reset- and Submit-Button.

When providing two buttons in a form, both buttons will be set as `type=submit` due to the behavior in the `componentWillLoad` where it searches for a closest `<form />`-Tag, which results in a submit-event disregarding its reset-type.

The Documentation states that I am able to provide a type-property which is completly ignored in this case.

Moving both buttons outside the form works, but is not a reliable solution.

**Comment by verena-ifx** [comment]
@tishoyanchev can you look into this?

**Comment by tishoyanchev** [comment]
> @tishoyanchev can you look into this?

@verena-ifx Yes, I'll take care of it.

**Comment by tishoyanchev** [comment]
@MichaelHolley 
Where does it say in the documentation that you can provide a type-property?
Also, which field component do you want to use the reset type for? 
The text field component we provide does not work with the type=reset functionality. So, you must have used a standard input field?

**Comment by tishoyanchev** [comment]
> @tishoyanchev
> 
> > Where does it say in the documentation that you can provide a type-property?
> 
> The "Development" & "Default" Subpage of the Button provides a control "type", but I just noticed that it has no effect at all on the generated code above in the example.
> 
> ![image](https://user-images.githubusercontent.com/47337897/279373280-ecbddb9f-43b3-4588-8342-998bd9a62c02.png)
> 
> > Also, which field component do you want to use the reset type for?
> 
> I simply want to have two ifx-buttons within a `<form />`-tag. Meaning that there a multiple textfields within this form, followed by a reset- and a submit-button. But both trigger the submit-event due to the behavior in `componentWillLoad `. This issue is independant of the ifx-textfield, as it does not fulfil our requirements at all, so we went with the native html inputs.

I will remove the storybook control options for button and submit. They're outdated. We used to allow it, but now we have automated the process, and the button becomes "type=submit" automatically when it's inside a form. 

As I said before, our text field component does not have an embedded function or way to "reset" its field, so using type=reset on a standard input element will not work with any of our components. If I am to add a type=reset to our button, then I would have to also modify the text field component to work with it. 

Where do we have a requirement to provide a type=reset on the button?

**Comment by MichaelHolley** [comment]
@tishoyanchev 

> Where do we have a requirement to provide a type=reset on the button?

Sorry this must be a misunderstanding. I ment "we" in context of a team/project using this component-lib. It is not a requirement on the behalf of this team.

**Comment by tishoyanchev** [comment]
> Sorry this must be a misunderstanding. I ment "we" in context of a team/project using this component-lib. It is not a requirement on the behalf of this team.

I have spoken with the relevant stakeholders regarding whether we should provide a type=reset kind of feature. I will let you know the collective decision. As I said, adding a type=reset like feature for clearing or canceling text-field input means modifying the text-field component as well.

**Comment by tishoyanchev** [comment]
> I believe that interpreting every button in a form-tag as a submit-button is simply wrong. Devs/Projects using this component lib should be able to include multiple buttons.
> 
> exemplary:
> 
> * reset
> * cancel
> * next/previous
> * preview
> * help
> * ...

I agree. There are plans for the introduction of a new Form component, and the idea was to include the various types of action inside the Form component rather than the Button component. But as I said, I have spoken with relevant stakeholders, and we will discuss your requirements and feedback.

**Comment by verena-ifx** [comment]
Hi @MichaelHolley, we have added the standard button types now 
you can now specify type button, submit or reset. The respective PR has already been merged onto master :)
