### ISSUE TITLE
Vue.JS wrapper: Events are not working

### ISSUE THREAD

**Issue by frankensimon** [Infineon/infineon-design-system-stencil#714]
**Prerequisites**

Can you reproduce the problem reliably?

Yes, the problem is reproducible.

Did you check current release notes for known issues?

Yes, found no known issue.

**Description**:

The custom events of the `Ifx`-components are not working. For example:

*Pagination*
- `@ifxPageChange`
- `@ifxNextPage`
- `@ifxPrevPage`

*Slider*
- `@ifxChange`

The type definition of the Vue.JS package contains these events, but they are never triggered. This is the case for **all** custom events I wanted to use so far. I assume there is a problem with the translation of the stencil events to the Vue.JS events. The only way to currently handle the custom events is to use `document.addEventListener()`, which is more a workaround than an alternative.

**Steps to Reproduce:**

1. Use any component which includes a custom event, for example the `IfxPagination`.
2. Add a handler to the `@ifxPageChange` event.
3. Change the page using the `IfxPagination` component.

```html
<IfxPagination @ifx-page-change="console.log" :total="10" :current-page="currentPage"></IfxPagination>
```

**Expected Result:**
The handler should be triggered when the page changes.

**Actual Result:**
Nothing happens, no event is emitted.

**Comment by verena-ifx** [comment]
I have updated the example in our example app folder for the Vue-Javascript application. (examples/wrapper-components/vue-javascript (PR: https://github.com/Infineon/infineon-design-system-stencil/pull/737)
The events work fine but the event handler needs to be written in camel case "@ifxPageChange", "@ifxNextPage" etc, as this is how they're defined in our Stencil components. Please let me know if this works for you.

**Comment by frankensimon** [comment]
Thank you for looking into it, I finally found out, why it hasn't been working for me.
To get the vue-wrapper events working, I had to do the following steps:
- Add the following code to the `vue()`-plugin in the `vite.config.ts` file found that in your [vite.config.ts file](https://github.com/Infineon/infineon-design-system-stencil/blob/master/examples/wrapper-components/vue-typescript/vite.config.ts)
 ```ts
vue({
      template: {
        compilerOptions: {
          // treat all tags with a dash as custom elements
          isCustomElement: (tag) => tag.includes("-"),
        },
      },
    })
```
- In the vue `<template>` replace 
```vue
<IfxSlider @ifx-change="console.log"></IfxSlider>
```
with 
```vue
<ifx-slider @ifxChange="console.log"></ifx-slider>
```

An alternative for these steps is, to just put the `IfxComponent` into a wrapper `div` and than catch the event on the `div`:
```vue
<div @ifxChange="console.log">
    <IfxSlider></IfxSlider>
</div>
```

Since the type declarations of the `infineon-design-system-vue` package suggests to use `<IfxSlider>` instead of `<ifx-slider>` and I also don't want to touch my `vite.config.ts` file, I decided to go with the second workaround.

Do you know why these extra steps are even necessary? Would it be possible to adapt the `infineon-design-system-vue` package, so that the suggested vue syntax (`<IfxSlider @ifx-change="console.log"></IfxSlider`) for events is working without any workarounds?
