### ISSUE TITLE
Pagination: Number of pages calculated incorrectly

### ISSUE THREAD

**Issue by MichaelHolley** [Infineon/infineon-design-system-stencil#715]
**Prerequisites**
Can you reproduce the problem reliably? YES

Did you check current release notes for known issues? YES

**Description**:
Providing a number of total items which is not modulo 10 == 0, results in not enough pages.

e.g. with 36 total items:
with 10 itemsPerPage -> 3 pages (should be 4)
with 20 itemsPerPage -> 1 page (should be 2)

**Steps to Reproduce:**

1. add a `ifx-pagination` component with 36 total item and 10 visible per page

**Expected Result:**
should be 4 pages

**Actual Result:**
3 pages

**Solution:**
Apply `Math.ceil` when calculating the number of pages
`const totalPageNumber = Math.ceil(total / itemsPerPage);`

**Comment by verena-ifx** [comment]
@tishoyanchev can you take a look here?

**Comment by tishoyanchev** [comment]
@MichaelHolley Great catch! Fixed it.
