### ISSUE TITLE
Table (advanced): Does not render Status-component

### ISSUE THREAD

**Issue by MichaelHolley** [Infineon/infineon-design-system-stencil#719]
The [documentation](https://infineon.github.io/infineon-design-system-stencil/?path=/docs/under-development-table-advanced--development#including-custom-components) states that I can include a Status-badge in a component.

This does not work.

Code to reproduce:

```Javascript
columns = [
    { headerName: 'Action', field: 'status' },
    ...
  ];
```

```Javascript
rows = [
    { status: 
        {
            label: 'LabelText,
            color: 'orange',
            border: true,
        },
      ... 
    }
  ];
```

which looks like this when rendered
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/47337897/515b2cdf-16f0-4743-91f0-a3c7e9ee1334)

**Comment by verena-ifx** [comment]
As the table (advanced) component was not in our initial scope, it cannot be handled as an issue with high priority right now. We will let you know once we will further develop this component
