### ISSUE TITLE
Extend ifx-text-field with more feature to allow more universal use.

### ISSUE THREAD

**Issue by benedikt-ifx** [Infineon/infineon-design-system-stencil#763]
**Is your feature request related to a problem? Please describe.**

The text field also need to be used for more complex searches, forms, filters and settings. Other components like the search field can not cover these cases as well.

**Describe the solution you'd like**

To allow the usage in the additional cases the text field needs a customizable icon and a delete content button similar to the search field while keeping the existing functionality

**Describe alternatives you've considered**

see above

**Additional context**

Request created by Michael Holley on Webex: webexteams://im?space=ffa4e010-a242-11ed-aa1b-3fd83b3f25e7&message=0bca31b0-8ded-11ee-a0f6-ed3bd45c9873

**Comment by tishoyanchev** [comment]
Re-opened here: https://github.com/Infineon/infineon-design-system-stencil/issues/1585
