### ISSUE TITLE
Set Filter for Table component

### ISSUE THREAD

**Issue by co-stig** [Infineon/infineon-design-system-stencil#771]
We use Tables extensively, and our users like the column filters. Some of the most important columns like Document State are enumerated, e.g. can be "Checked out", "Released" or "Checked in". Right now the text filters is the only way to filter on those. 

We would like to give our users the [Set Filter](https://www.ag-grid.com/javascript-data-grid/filter-set/) functionality, so that they can choose the values from a list.

**Describe the solution you'd like**

See the link above, or similar.

I understand that this is an Enterprise feature of AG Grid, but then we need to have at least a way to plug an Enterprise license (key?) into the component somehow, so that it's available.

**Describe alternatives you've considered**

1. Using plaintext filtering -- not as convenient
2. Move filters outside of the Table -- requires extra code, doesn't look as good
3. Replace it with Kendo UI Grid (for which we have a license) -- to make its styling and behavior consistent with the rest of the components we'd have to write significant amount of custom code

**Comment by tishoyanchev** [comment]
Filter is being implemented in another Issue: https://github.com/Infineon/infineon-design-system-stencil/pull/988
