### ISSUE TITLE
Line under tab not rendered in Vue 2.6

### ISSUE THREAD

**Issue by matthiassommer** [Infineon/infineon-design-system-stencil#801]
**Prerequisites**

Can you reproduce the problem reliably?
Yes

**Description**:

The green line under each tab is not visible and does also not appear when a tab is clicked.

**Steps to Reproduce:**
```
<ifx-tabs>
      <ifx-tab
        :header="$t('admin.manage-software-and-tools.tabs.software')"
        @ifxTabIndex="setActiveTab(TAB_SOFTWARE)"
      >
        <b-overlay :show="isLoading">
          <software-overview :tools="software" />
        </b-overlay>
      </ifx-tab>
      <ifx-tab
        :header="$t('admin.manage-software-and-tools.tabs.tools')"
        @ifxTabIndex="setActiveTab(TAB_TOOLS)"
      >
        <b-overlay :show="isLoading">
          <software-overview :tools="tools" />
        </b-overlay>
      </ifx-tab>
</ifx-tabs>
```

**Expected Result:**

Green line beneath active tab.

**Actual Result:**
![grafik](https://github.com/Infineon/infineon-design-system-stencil/assets/28532316/2751069d-ad9d-4d06-a992-26883089b8ef)

**Environment**
Vue 2.6
"@infineon/infineon-design-system-stencil": "^20.34.5"
<script type="module" src="https://cdn.jsdelivr.net/npm/@infineon/infineon-design-system-stencil/dist/infineon-design-system-stencil/infineon-design-system-stencil.esm.js"></script>
Firefox, Chrome

**Comment by verena-ifx** [comment]
There is an open PR for the Tab component. I hope we can merge that one today - maybe this will fix the issue, but we do not specifically test our components in applications using Vue 2 at the moment.

**Comment by tishoyanchev** [comment]
@matthiassommer 
I will close this issue because it's not occurring on Vue 3, and we do not support Vue 2.
