### ISSUE TITLE
Set consistent padding values for navbar and footer components

### ISSUE THREAD

**Issue by roman-vi** [Infineon/infineon-design-system-stencil#811]
**navbar and footer components padding strategy and values are different**

Padding for footer is fixed 0 32px, for navbar it depends on screen width by @media query.

**Adapt footer padding with @media query**

Set the same padding rules for footer component as it's set for navbar.

**Comment by tishoyanchev** [comment]
@radikantchris @benedikt-ifx Could you look at this issue, and give us your perspective?

**Comment by roman-vi** [comment]
I just thought about an alternative. 'part' attribute could be set to html tags.

**Comment by tishoyanchev** [comment]
@SergejLust What do you think about this?

**Comment by tishoyanchev** [comment]
Mobile version of the Footer has been implemented
