### ISSUE TITLE
unable to test new component locally within typescript example application 

### ISSUE THREAD

**Issue by akashyeole** [Infineon/infineon-design-system-stencil#846]
Description:
If you develop a new component, lets call it 'stepper', in components folder and want to test it locally(in folder examples/wrapper-components) using 'npm run test:local' then you get the errors that are shown in the image below. The issue is only with the react-typescript and vue-typescript and not with javascipt.

Steps to reproduce:
*Develop any new component in 'packages/components' or checkout '752-component-stepper'
1) Go to 'examples/wrapper-components/react-typescript'
2) run 'npm i'
3) run 'npm run test:local'

Environment:
Node v20.5.0 (latest)
NPM v10.2.3

Note:
Similar issue in javascript wrapper components was fixed by @verena-ifx 

![image](https://github.com/Infineon/infineon-design-system-stencil/assets/97229205/64b0d71f-cb0a-4cbb-8df7-5ccb3b36affb)

**Comment by tishoyanchev** [comment]
@akashyeole Could you please provide more information in the description, such as how steps to reproduce, working environment (where you are running it, and how), and any other relevant information.

**Comment by dmytro-infineon** [comment]
@tishoyanchev I guess `react-typescript example` is simply outdated. 
When I run `npm run dev` in my console I have `Uncaught SyntaxError: ambiguous indirect export: IfxNavbarItem`
And if you open `Navbar.tsx` you see all those errors highlighted.

**Comment by akashyeole** [comment]
@tishoyanchev 
This issue can be marked as resolved as the typescript applications are working fine now.

**Comment by tishoyanchev** [comment]
Resolved
