### ISSUE TITLE
Select component changes global font-family

### ISSUE THREAD

**Issue by arapd** [Infineon/infineon-design-system-stencil#850]
**Prerequisites**

Can you reproduce the problem reliably?
Yes

Did you check current release notes for known issues?
Yes

If this is not the latest release, have you checked newer releases? 
No, using latest (20.37.4)

**Description**:
The `ifx-select` component is overwriting the font-family globally, when loaded.
We defined a specific font for our site, which is never changed. However we discovered, that whenever the `ifx-select` component
has been added and loaded, the global font-family was overwritten with `Source Sans 3`, which should not happen.

**Steps to Reproduce:**

1. Create empty page/component and set a global font-family to anything other than `Source Sans 3`

2. Run page and check browser that the font-family is set

3. Add simple `<ifx-select></ifx-select>` element, which gets loaded and rendered

4. Check browser and verify that font-family set in step 1 has been changed to `Source Sans 3`

**Expected Result:**
Font-Family outside of the ifx-select element does not get altered

**Actual Result:**
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/56158137/6d25b94a-6ce0-42e4-8a2f-670bf20cc58b)

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**
20.37.4

**Host OS and Version:**
Windows 10

**Environment**

Vue 2.6
"@infineon/infineon-design-system-stencil": "^20.37.4"

<script type="module" src="https://cdn.jsdelivr.net/npm/@infineon/infineon-design-system-stencil/dist/infineon-design-system-stencil/infineon-design-system-stencil.esm.js"></script>
Firefox, Chrome

**Comment by tom-weisser-aracom** [comment]
I might add that this problem also exists for the table component and probably others (E.g. https://github.com/Infineon/infineon-design-system-stencil/blob/d7f977904b60af8cd29b876d8da61484c9cab2e6/packages/components/src/components/table/table.scss#L2). All components that use https://github.com/Infineon/infineon-design-system-stencil/blob/master/packages/components/src/global/font.scss in their .scss file probably have the same behavior regarding the font-family. 
So i am not sure, whether this is desired, but it makes it more difficult to use the DDS in conjunction with some other font-family.

**Comment by tishoyanchev** [comment]
@arapd @tom-weisser-aracom 
Thank you for the feedback. 
It is generally not our intent to modify the global fonts, however, it is a requirement for external facing apps to comply with our DDS design, which includes the font family. If your app is internal, it is not a requirement, but a strong suggestion that you use our DDS font-family. Still, nevertheless, components should not set global font-family. I have added this issue in our backlog, and we'll be working on it!

**Comment by matthiassommer** [comment]
We have faced the same issue with the basic table.
