### ISSUE TITLE
Progress bar container background

### ISSUE THREAD

**Issue by akashyeole** [Infineon/infineon-design-system-stencil#880]
In the component- progress bar, the container background is transparent, where as in the [figma design](https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=2393-3988&mode=design&t=vfbC1KdNUYYnE3Pk-0) of it, it has color gray.
I think this gray color is useful because it helps to indicate the remaining progress if the label is disabled. 
Just wanted to know if that'a a bug or it was decided to keep it transparent?

Screenshot:
Current-
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/97229205/5554843e-db96-4c7d-a72e-a988f50954a0)

If we add bgc (It looks good)-
![image](https://github.com/Infineon/infineon-design-system-stencil/assets/97229205/ddca887a-d32a-48d2-895b-8d0c7f37ed4b)

**Comment by tishoyanchev** [comment]
@akashyeole 
It's not a bug. It's just a change in the design after the component was already released. 
Yes, we have to edit the component to comply with the design.
