### ISSUE TITLE
Tabs: tabIndex is not consistent

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#887]
When you first press the tab key, tab 1 is focused. On second press, tab 2 is focused. 
However, if you then click with the mouse on any of the tabs, and then click outside the Tab component, then pressing the tab key will focus only the last tab that was clicked, and continuingly pressing the tab key will not focus the next tab in order, but will focus outside the Tab component.

**Comment by verena-ifx** [comment]
see: https://github.com/Infineon/infineon-design-system-stencil/issues/944
