### ISSUE TITLE
Radio Button Group

### ISSUE THREAD

**Issue by benedikt-ifx** [Infineon/infineon-design-system-stencil#909]
Create the design for a radio button group.

There should be a vertical and horizontal layout.

There should be a property in Figma where I can select the number of items in the group.

**Comment by radikantchris** [comment]
The **Radiobutton group** is now available in our MainDDS FIGMA File. 
(https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%257C-Main?type=design&node-id=47105-6412&mode=design&t=noTrDvmmiGrRewPc-4)

Properties:
- **Type** (is set to default)
This function is intended to cover any future requirements for a compressed version (smaller spacing between the vertical radiobuttons if space is limited)
- **aligment** (horizontal/vertical)
- **amount** (2,3,4,5)
