### ISSUE TITLE
Sidebar: add url props to storybook controls

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#919]
Add the URL props for: applicationName, termsOfUse and Imprint on Storybook so users know they are configurable.

**Comment by verena-ifx** [comment]
is this not done yet? @tishoyanchev

**Comment by tishoyanchev** [comment]
@verena-ifx 
Currently, we are only showing control option for the **application-name** in Storybook. We should also add those for the **termsOfUse**, **privacy policy** and **Imprint** so users can know that those are also customizable.

**Comment by akashyeole** [comment]
@tishoyanchev 
this was fixed in the PR #994 
We can close this issue
