### ISSUE TITLE
Footer: links should be removable

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#963]
terms of use, imprint, privacy policy and glossary links should be removable.

**Comment by dmytro-infineon** [comment]
I'd say adjustable ;)

**Comment by tishoyanchev** [comment]
> I'd say adjustable ;)
@dmytro-infineon 
What do you mean by "adjustable"?

**Comment by dmytro-infineon** [comment]
Everything I wanted to say you already described in https://github.com/Infineon/infineon-design-system-stencil/issues/966 ;)
