### ISSUE TITLE
How to adjust Dropdown width?

### ISSUE THREAD

**Issue by ghost** [Infineon/infineon-design-system-stencil#964]
Hi !

I noticed that `Dropdown` component has hardcoded `width: 224px` and if `DropdownItem` has long long word in title inside (unfortunately happens in hardware naming)  than horizontal scrollbar appears inside open dropdown.

Would it be possible to adjust `width: 224px` maybe to be `min-width: 224px` ?

Thank you in advance.

**Comment by tishoyanchev** [comment]
Hi,
Thank you for pointing out this issue to us.
We will look into it.
