### ISSUE TITLE
Bug: Multiselect incorrect styling of indeterminate option when deselecting sub-option

### ISSUE THREAD

**Issue by verena-ifx** [Infineon/infineon-design-system-stencil#968]
When deselecting a sub-option in the Multiselect, after the parent has been selected, the parent should be marked as indeterminate (which it does), but the checkmark doesnt get removed, so the styling shows both the checkmark + the indeterminate symbol.
the checkmark should be removed in this case.

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx  
Feel free to open another branch.
