### ISSUE TITLE
Tailwind-DDS Project: Part 4 - Grid layout

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#972]
As part 4 of the Tailwind-DDS project, provide CSS classes for a Grid layout. 

Part 1: https://github.com/Infineon/infineon-design-system-stencil/issues/969
Part 2: https://github.com/Infineon/infineon-design-system-stencil/issues/970
Part 3: https://github.com/Infineon/infineon-design-system-stencil/issues/971

**Comment by benedikt-ifx** [comment]
Grid can be defined by customizing 'grid-template-column' in 'theme.gridTemplateColumns' in the 'tailwind.config.js' file.
