### ISSUE TITLE
Multiselect: when select is set to true on an option, its checkbox remains unchecked on the menu

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#991]
If "**selected**" is set to "**true**" when passing an option, eg: `{"value":"a","label":"option a","selected":true}`, then that option is not marked as checked on the menu.

**Comment by verena-ifx** [comment]
yes, that is disregarded, as that object just contains the original status. but it is emitted correctly.
it is a minor improvement that can be done of course. Or we simply remove the selected prop from the emtitted object completely? @tishoyanchev

**Comment by tishoyanchev** [comment]
@verena-ifx 
The **selected** property allows users to set a default selected option, which is necessary to have in my opinion. It is only counterintuitive and unexpected that when you pass an option that is selected by default, it's not showing as selected in the menu when you open it. Would this require a lot of effort to implement?
